version: "3"
services: 
    react-app:
        # stdin_open: true
        # tty: true
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes:
            - ./src:/app/src
        environment: 
            - REACT_APP_NAME=frontend-dev
            - CHOKIDAR_USEPOLLING=true
        # env_file: 
        #     - ./.env
        #Para efetuar o build:
            #docker-compose -f docker-compose.yml -f docker-compose-dev.yml up -d --build
        #Para desfazer o build:
            #docker-compose -f docker-compose.yml -f docker-compose-dev.yml down